
name: Android CI


on: [pull_request, push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:

      - name: Checkout the code
        uses: actions/checkout@v2

      - name: Upload
        run: actions/upload-pages-artifact 

      - name: deploy
        run: actions/deploy-pages 

