
name: Android CI


on: [pull_request, push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:

      - name: Checkout the code
        uses: actions/checkout@v2

      - name: Upload static files
        uses: actions/upload-pages-artifact

      - name: Deploy
        uses: actions/deploy-pages
