
name: Android CI


# Événements sur lesquels il doit être déclenché
on:
  push:         # <- Déclenché lorsque l'on pousse du code...
    branches:
      - master  # <- ... mais seulement sur la branche "master"

 
jobs:

  # Notre job
  build-and-deploy:
    runs-on: ubuntu-latest

    # Tâches à effectuer, comme expliquées ci-dessus
    steps:

      # 1. On récupère le contenu du dépôt

      - name: "Checkout"
        uses: actions/checkout@v2
      
      - name: "jekyll"
        uses: actions/jekyll-build-pages@v1

      - name: "upload"
        uses: actions/upload-pages-artifact@v1