name: Mag Togo Landing Page

on:
  push:
  branches: [ master ] # comment-out to specify any branch. ex: master etc.

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Upload static files
        uses: actions/upload-pages-artifact

      - name: Deploy
        uses: actions/deploy-pages